regions_ru  = {'Алтайский край':'Altai Krai',
 'Республика Алтай':'Altai Republic',
 'Амурская область':'Amur Oblast',
 'Архангельская область':'Arkhangelsk Oblast',
 'Астраханская область': 'Astrakhan Oblast',
 'Белгородская область':'Belgorod Oblast',
 'Брянская область':'Bryansk Oblast',
 'Чеченская Республика':'Chechen Republic',
 'Челябинская область':'Chelyabinsk Oblast',
 'Чукотский автономный округ':'Chukotka Autonomous Okrug',
 'Чувашская Республика':'Chuvash Republic',
 'Иркутская область': 'Irkutsk Oblast',
 'Ивановская область': 'Ivanovo Oblast',
 'Еврейская автономная область': 'Jewish Autonomous Oblast',
 'Кабардино-Балкарская Республика': 'Kabardino-Balkar Republic',
 'Калининградская область': 'Kaliningrad Oblast',
 'Калужская область': 'Kaluga Oblast',
 'Камчатский край': 'Kamchatka Krai',
 'Карачаево-Черкесская Республика':'Karachay-Cherkess Republic',
 'Кемеровская область': 'Kemerovo Oblast',
 'Хабаровский край': 'Khabarovsk Krai',
 'Ханты-Мансийский автономный округ - Югра':'Khanty–Mansi Autonomous Okrug – Yugra',
 'Кировская область': 'Kirov Oblast',
 'Республика Коми':'Komi Republic',
 'Костромская область': 'Kostroma Oblast',
 'Краснодарский край': 'Krasnodar Krai',
 'Красноярский край': 'Krasnoyarsk Krai',
 'Курганская область': 'Kurgan Oblast',
 'Курская область': 'Kursk Oblast',
 'Ленинградская область': 'Leningrad Oblast',
 'Липецкая область': 'Lipetsk Oblast',
 'Магаданская область': 'Magadan Oblast',
 'Республика Марий Эл':'Mari El Republic',
 'Москва': 'Moscow',
 'Московская область':'Moscow Oblast',
 'Мурманская область': 'Murmansk Oblast',
 'Ненецкий автономный округ':'Nenets Autonomous Okrug',
 'Нижегородская область': 'Nizhny Novgorod Oblast',
 'Новгородская область':'Novgorod Oblast',
 'Новосибирская область':'Novosibirsk Oblast',
 'Омская область':'Omsk Oblast',
 'Оренбургская область':'Orenburg Oblast',
 'Орловская область': 'Oryol Oblast',
 'Пензенская область':'Penza Oblast',
 'Пермский край':'Perm Krai',
 'Приморский край':'Primorsky Krai',
 'Псковская область':'Pskov Oblast',
 'Республика Адыгея':'Republic of Adygea',
 'Республика Башкортостан':'Republic of Bashkortostan',
 'Республика Бурятия':'Republic of Buryatia',
 'Республика Крым':'Republic of Crimea',
 'Республика Дагестан':'Republic of Dagestan',
 'Республика Ингушетия':'Republic of Ingushetia',
 'Республика Калмыкия':'Republic of Kalmykia',
 'Республика Карелия':'Republic of Karelia',
 'Республика Хакасия':'Republic of Khakassia',
 'Республика Мордовия':'Republic of Mordovia',
 'Республика Северная Осетия - Алания': 'Republic of North Ossetia-Alania',
 'Республика Татарстан':'Republic of Tatarstan',
 'Ростовская область': 'Rostov Oblast',
 'Рязанская область': 'Ryazan Oblast',
 'Санкт-Петербург': 'Saint Petersburg',
 'Республика Саха (Якутия)':'Sakha (Yakutia) Republic',
 'Сахалинская область':'Sakhalin Oblast',
 'Самарская область': 'Samara Oblast',
 'Саратовская область': 'Saratov Oblast',
 'Севастополь':'Sevastopol',
 'Смоленская область':'Smolensk Oblast',
 'Ставропольский край':'Stavropol Krai',
 'Свердловская область':'Sverdlovsk Oblast',
 'Тамбовская область':'Tambov Oblast',
 'Томская область':'Tomsk Oblast',
 'Тульская область':'Tula Oblast',
 'Республика Тыва': 'Tuva Republic',
 'Тверская область':'Tver Oblast',
 'Тюменская область':'Tyumen Oblast',
 'Удмуртская Республика':'Udmurt Republic',
 'Ульяновская область':'Ulyanovsk Oblast',
 'Владимирская область': 'Vladimir Oblast',
 'Волгоградская область': 'Volgograd Oblast',
 'Вологодская область': 'Vologda Oblast',
 'Воронежская область': 'Voronezh Oblast',
 'Ямало-Ненецкий автономный округ': 'Yamalo-Nenets Autonomous Okrug',
 'Ярославская область':'Yaroslavl Oblast',
 'Забайкальский край': 'Zabaykalsky Krai'}
